version: "3"
services:
  mysql:
    image: 8sistemas/laravel-alpine:8.1-mysql
    user: "82:82"
    read_only: true
    tmpfs:
      - /tmp
      - /run/nginx
      - /var/lib/nginx/tmp
    cap_drop:
      - ALL
  mysql-nginx:
    image: 8sistemas/laravel-alpine:8.1-mysql-nginx
    user: "82:82"
    read_only: true
    environment:
      - ENV_VAR_FROM_DOCKER_COMPOSE=test
    tmpfs:
      - /tmp
      - /run/nginx
      - /var/lib/nginx/tmp
    cap_drop:
      - ALL
    ports:
      - 9090:8080
  pgsql:
    image: 8sistemas/laravel-alpine:8.1-pgsql
    user: "82:82"
    read_only: true
    tmpfs:
      - /tmp
      - /run/nginx
      - /var/lib/nginx/tmp
    cap_drop:
      - ALL
  pgsql-nginx:
    user: "82:82"
    read_only: true
    environment:
      - ENV_VAR_FROM_DOCKER_COMPOSE=test
    tmpfs:
      - /tmp
      - /run/nginx
      - /var/lib/nginx/tmp
    cap_drop:
      - ALL
    image: 8sistemas/laravel-alpine:8.1-pgsql-nginx
    ports:
      - 9091:8080