name: Build PHP8.1
on:
  push:
    branches: [master]
  schedule:
    - cron: "0 0 1,15 * *"
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: eightsystems/laravel-alpine
jobs:
  build-images:
    runs-on: ubuntu-latest
    if: (!contains(github.event.head_commit.message, '[skipci]') && !contains(github.event.head_commit.message, '[noci]'))
    strategy:
      max-parallel: 12
      matrix:
        php: ["7.4", "8.0", "8.1"]
        variant: ["mysql", "mysql-nginx", "pgsql-nginx", "pgsql"]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.php }}/${{ matrix.variant }}/
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.php }}-${{ matrix.variant }}
          labels: ${{ steps.meta.outputs.labels }}
